### ISSUE TITLE
大佬分析一下我这的问题出在哪里

### ISSUE THREAD

**Issue by 420348264** [silie666/sina_luck_draw#5]
~/gop/sina_luck_draw $ ./sina

2022/08/12 09:44:41 /data/data/com.termux/files/home/gop/sina_luck_draw/drivers/mysql/mysql.go:31
[error] failed to initialize database, got error dial tcp 127.0.0.1:8888: connect: connection refused
panic: database data source name error: dial tcp 127.0.0.1:8888: connect: connection refused

goroutine 1 [running]:
sina/drivers/mysql.init.0()
        /data/data/com.termux/files/home/gop/sina_luck_draw/drivers/mysql/mysql.go:47 +0x4a0

**Comment by silie666** [comment]
> 

数据库连接失败

**Comment by silie666** [comment]
> ~/gop/sina_luck_draw $ ./sina
> 
> 2022/08/12 09:44:41 /data/data/com.termux/files/home/gop/sina_luck_draw/drivers/mysql/mysql.go:31 [error] failed to initialize database, got error dial tcp 127.0.0.1:8888: connect: connection refused panic: database data source name error: dial tcp 127.0.0.1:8888: connect: connection refused
> 
> goroutine 1 [running]: sina/drivers/mysql.init.0() /data/data/com.termux/files/home/gop/sina_luck_draw/drivers/mysql/mysql.go:47 +0x4a0

数据库连接失败

**Comment by 420348264** [comment]
![image](https://user-images.githubusercontent.com/8722979/184333426-1ce16553-51cd-4d94-8170-da33f908f72a.jpeg)

**Comment by 420348264** [comment]
> > ~/gop/sina_luck_draw $ ./sina
> 
> > 
> 
> > 2022/08/12 09:44:41 /data/data/com.termux/files/home/gop/sina_luck_draw/drivers/mysql/mysql.go:31 [error] failed to initialize database, got error dial tcp 127.0.0.1:8888: connect: connection refused panic: database data source name error: dial tcp 127.0.0.1:8888: connect: connection refused
> 
> > 
> 
> > goroutine 1 [running]: sina/drivers/mysql.init.0() /data/data/com.termux/files/home/gop/sina_luck_draw/drivers/mysql/mysql.go:47 +0x4a0
> 
> 
> 
> 数据库连接失败

你看下图片，我跟着教程弄得，就到这一步不行了，我用手机弄得。我该怎么处理呢，我是小白，能大概指导一下吗
